name: Pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
    - name: Analysing the code with pylint
      run: |
        pylint --ignore-patterns=test_.*?py --disable=missing-module-docstring,unspecified-encoding,useless-return,keyword-arg-before-vararg,consider-using-dict-items,too-many-instance-attributes,consider-iterating-dictionary,too-many-arguments,inconsistent-return-statements,line-too-long,broad-exception-caught $(git ls-files '*.py')
